model_list:
  - model_name: claude-sonnet-4-5-20250929
    litellm_params:
      model: os.environ/TARGET_MODEL_NAME
      api_base: os.environ/ANTHROPIC_BASE_URL
      api_key: os.environ/MODELARTS_API_KEY
      custom_llm_provider: os.environ/CUSTOM_LLM_PROVIDER
      stream: true
      drop_params: true
  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: os.environ/TARGET_MODEL_NAME
      api_base: os.environ/ANTHROPIC_BASE_URL
      api_key: os.environ/MODELARTS_API_KEY
      custom_llm_provider: os.environ/CUSTOM_LLM_PROVIDER
      stream: true
      drop_params: true
litellm_settings:
    ssl_verify: false
    drop_params: true
    translate_tools: true
