[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[theme]
font = "sans serif"

[theme.dark]
primaryColor = "#82aaff"
backgroundColor = "#011627"
secondaryBackgroundColor = "#0b253a"
textColor = "#d6deeb"
borderColor = "#5f7e97"

[theme.light]
primaryColor = "#275f92"
backgroundColor = "#FBFBFB"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#403f53"
borderColor = "#d6deeb"