package com.vmscheduling.model;

import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import lombok.Getter;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * A logical grouping of NUMA nodes within a host.
 * Pre-computes all combinatorial placements as NUMAs are added.
 *
 * See 05-placement-precomputation.md for the addNuma() algorithm.
 */
@Getter
public class NumaGroup {

    private final Host host;
    private final List<Numa> numas;
    private final List<List<Placement>> placements; // placements[k-1] = all k-NUMA placements

    public NumaGroup(Host host) {
        this.host = host;
        this.numas = new ObjectArrayList<>();
        this.placements = new ObjectArrayList<>();
    }

    /**
     * Adds a new NUMA node and generates all new combinatorial placements.
     * Each time a Numa is added, all possible placements using that node are
     * generated by extending existing k-placements into (k+1)-placements.
     *
     * Confirmed source from MainWiki §3.6 / 05-placement-precomputation.md.
     */
    public Numa addNuma(List<Numa> allNumas) {
        Numa numa = new Numa(this, numas.size(), allNumas.size());
        numas.add(numa);
        allNumas.add(numa);
        placements.add(new ObjectArrayList<>());

        // Combinatorial expansion: extend every existing k-placement into (k+1)-placement
        for (int i = placements.size() - 2; i >= 0; --i) {
            for (Placement placement : placements.get(i)) {
                Numa[] newNumas = Arrays.copyOf(placement.getNumas(), i + 2);
                newNumas[i + 1] = numa;
                placements.get(i + 1).add(new Placement(newNumas));
            }
        }
        // Add single-numa placement for this new node
        placements.get(0).add(new Placement(new Numa[]{numa}));

        return numa;
    }

    /**
     * Returns all possible Placements using exactly numNumas nodes — O(1) lookup.
     * For a NumaGroup with N numas, getPlacements(k) returns all C(N,k) combinations.
     */
    public List<Placement> getPlacements(int numNumas) {
        if (numNumas > placements.size()) return Collections.emptyList();
        return placements.get(numNumas - 1);
    }
}
