"""
Candidate Manager for LLM-Generated Strategies

Handles:
- Candidate directory layout and lifecycle
- Compilation delegation to a pluggable BaseBuilder
- Caching by code hash
- Metadata tracking (parent IDs, prompts, timestamps)
"""

import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

from loguru import logger

from building import BaseBuilder


class CandidateManager:
    """Manages the lifecycle of plugin candidates.

    Domain-agnostic: all compilation is delegated to an injected BaseBuilder.
    Handles caching, directory creation, and metadata persistence.
    """

    def __init__(self,
                 candidates_dir: str = "candidates",
                 builder: Optional[BaseBuilder] = None,
                 cache_file: str = "candidates/cache.json"):
        """
        Initialize candidate manager.

        Args:
            candidates_dir: Directory for storing candidate files
            builder: BaseBuilder instance for compilation. Domain-agnostic — any
                     BaseBuilder subclass is accepted (injected by EvolutionLoop).
            cache_file: Path to cache database
        """
        self.candidates_dir = Path(candidates_dir)
        self.cache_file = Path(cache_file)
        self.builder = builder

        # Create directories
        self.candidates_dir.mkdir(exist_ok=True)

        # Load cache
        self.cache = self._load_cache()

    # ------------------------------------------------------------------
    # Cache helpers
    # ------------------------------------------------------------------

    def _load_cache(self) -> Dict[str, Dict[str, Any]]:
        if self.cache_file.exists():
            with open(self.cache_file) as f:
                return json.load(f)
        return {}

    def _save_cache(self):
        self.cache_file.parent.mkdir(exist_ok=True)
        with open(self.cache_file, "w") as f:
            json.dump(self.cache, f, indent=2)

    # ------------------------------------------------------------------
    # Build API
    # ------------------------------------------------------------------

    def build_candidate(self,
                        source_code: str,
                        candidate_id: int,
                        idea: Optional[str] = None,
                        generation: int = 0,
                        parent_id: Optional[int] = None,
                        mutation_type: str = "initial") -> Optional[Dict[str, Any]]:
        """Build a candidate plugin (compile + package).

        Args:
            source_code: Source code generated by the LLM
            candidate_id: Unique candidate ID
            idea: High-level idea/concept description
            generation: Generation number for tagging idea files
            parent_id: Parent candidate ID (if mutation/crossover)
            mutation_type: Type of generation (initial, mutation, crossover)

        Returns:
            Metadata dict with at least "artifact_path" and "entry_point", or None if failed.
        """
        if self.builder is None:
            logger.error("[CANDIDATE MANAGER] No builder configured — cannot build candidate")
            return None

        # Check cache
        code_hash = hashlib.sha256(source_code.encode()).hexdigest()
        if code_hash in self.cache:
            logger.debug(f"[CACHE HIT] Candidate {candidate_id} matches cached code")
            cached = self.cache[code_hash].copy()
            cached["candidate_id"] = candidate_id
            return cached

        # Create candidate directory
        candidate_dir = self.candidates_dir / f"gen_{candidate_id:04d}"
        candidate_dir.mkdir(exist_ok=True)

        # Delegate compilation to builder
        build_result = self.builder.build(
            source_code=source_code,
            candidate_id=candidate_id,
            candidate_dir=str(candidate_dir),
        )

        if not build_result:
            return None

        # Build metadata (domain-agnostic core fields)
        metadata: Dict[str, Any] = {
            "candidate_id": candidate_id,
            "parent_id": parent_id,
            "mutation_type": mutation_type,
            "idea": idea,
            "artifact_path": build_result["artifact_path"],
            "entry_point": build_result["entry_point"],
            "code_hash": code_hash,
            "timestamp": datetime.now().isoformat(),
            "candidate_dir": str(candidate_dir),
        }
        # Merge any extra domain-specific fields from the builder
        for k, v in build_result.items():
            if k not in ("artifact_path", "entry_point"):
                metadata[k] = v

        # Save metadata JSON
        metadata_file = candidate_dir / "metadata.json"
        with open(metadata_file, "w") as f:
            json.dump(metadata, f, indent=2)

        # Save idea to generation-tagged file
        if idea:
            idea_file = candidate_dir / f"idea_gen{generation:04d}.md"
            with open(idea_file, "w") as f:
                f.write(f"# Generation {generation} - Candidate {candidate_id}\n\n")
                f.write(f"**Mutation Type:** {mutation_type}\n\n")
                if parent_id is not None:
                    f.write(f"**Parent ID:** {parent_id}\n\n")
                f.write(f"## Idea\n\n{idea}\n")

        # Update cache
        self.cache[code_hash] = metadata
        self._save_cache()

        logger.debug(f"[BUILT] Candidate {candidate_id} -> {build_result['artifact_path']}")
        return metadata

    # Keep the old name as an alias for backward compatibility
    def compile_candidate(self,
                          strategy_code: str,
                          candidate_id: int,
                          idea: Optional[str] = None,
                          generation: int = 0,
                          parent_id: Optional[int] = None,
                          mutation_type: str = "initial") -> Optional[Dict[str, Any]]:
        """Deprecated alias for build_candidate()."""
        return self.build_candidate(
            source_code=strategy_code,
            candidate_id=candidate_id,
            idea=idea,
            generation=generation,
            parent_id=parent_id,
            mutation_type=mutation_type,
        )

    # ------------------------------------------------------------------
    # Metadata helpers
    # ------------------------------------------------------------------

    def get_candidate_info(self, candidate_id: int) -> Optional[Dict[str, Any]]:
        """Get metadata for a candidate by ID."""
        candidate_dir = self.candidates_dir / f"gen_{candidate_id:04d}"
        metadata_file = candidate_dir / "metadata.json"
        if metadata_file.exists():
            with open(metadata_file) as f:
                return json.load(f)
        return None

    def update_evaluation_results(self,
                                   candidate_id: int,
                                   eval_results: list,
                                   fitness: float,
                                   base_fitness: float,
                                   generation: int = 0,
                                   score_vector: dict = None) -> bool:
        """Update candidate metadata with evaluation results."""
        candidate_dir = self.candidates_dir / f"gen_{candidate_id:04d}"
        metadata_file = candidate_dir / "metadata.json"

        if not metadata_file.exists():
            return False

        with open(metadata_file) as f:
            metadata = json.load(f)

        metadata["evaluation"] = {
            "generation": generation,
            "fitness": fitness,
            "fitness_pct": fitness * 100,
            "base_fitness": base_fitness,
            "base_fitness_pct": base_fitness * 100,
            "num_instances": len(eval_results),
            "instances": [],
        }

        if score_vector is not None:
            metadata["evaluation"]["score_vector"] = score_vector

        for result in eval_results:
            metadata["evaluation"]["instances"].append({
                "name": result.get("instance", "unknown"),
                "warmstart_cost": result.get("warmstart_cost", 0),
                "final_cost": result.get("final_cost", 0),
                "improvement": result.get("improvement", 0),
                "improvement_pct": result.get("improvement", 0) * 100,
                "runtime": result.get("runtime", 0),
                "success": result.get("success", False),
            })

        with open(metadata_file, "w") as f:
            json.dump(metadata, f, indent=2)

        code_hash = metadata.get("code_hash")
        if code_hash and code_hash in self.cache:
            self.cache[code_hash] = metadata
            self._save_cache()

        return True

    def list_candidates(self) -> list:
        """List all compiled candidates."""
        candidates = []
        for candidate_dir in sorted(self.candidates_dir.glob("gen_*")):
            metadata_file = candidate_dir / "metadata.json"
            if metadata_file.exists():
                with open(metadata_file) as f:
                    candidates.append(json.load(f))
        return candidates
